title: Industrial Workers of the World · Detroit
email: detroit@iww.org
baseurl: ""
url: "https://detroitiww.org"
description: The latest news and happenings from the Detroit Industrial Workers of the World! · An injury to one is an injury to all.

future: true

paypal: 

logo: /assets/logo.png

defaults:
  - scope:
      path: ""
    values:
      image: /assets/footer.png

twitter_username: DetroitIWW
instagram_username: 
facebook_username: DetroitIWW
mastodon_username: 
github_username: DetroitIWW
keybase_username: 

social:
  name: Detroit IWW GMB
  links:
    - https://twitter.com/DetroitIWW
    - https://facebook.com/DetroitIWW
    - https://github.com/DetroitIWW

twitter:
  username: DetroitIWW
  card: summary

facebook:
  publisher: DetroitIWW

markdown: kramdown

kramdown:
  parse_span_html: true
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  events:
    output: true
    path: ""
    permalink: /events/:path/
  news:
    output: true
    path: ""
    permalink: /news/:path/

paginate: 5
paginate_path: "/news/:num/"
